using System.Text.Json.Serialization;

namespace Lavabird.Amplitude.Api;

public class AmplitudeBase
{
	/// <summary>
	/// ID of the user responsible for this event. Can be a generated anonymous ID. One of either a UserID or DeviceID
	/// must be set when calling the Amplitude API.
	/// </summary>
	[JsonPropertyName("user_id")]
	public string? UserId { get; }
    
	/// <summary>
	/// The unique ID for the device responsible for this event. One of either a UserID or DeviceID must be set when
	/// calling the Amplitude API. If a DeviceId isn't sent with the event, then a hashed version of the UserId will
	/// be generated by Amplitude.
	/// </summary>
	[JsonPropertyName("device_id")]
	public string? DeviceId { get; }

	protected AmplitudeBase(AmplitudeIdentity identity)
	{
		UserId = identity.UserId;
		DeviceId = identity.DeviceId;
	}
}